version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    container_name: simplewap_web
    volumes:
      - ./:/var/www
    ports:
      - "8000:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    container_name: simplewap_app
    volumes:
      - ./:/var/www
    links:
      - database

  database:
    image: mysql:5.6
    container_name: simplewap_mysql
    environment:
        MYSQL_ROOT_PASSWORD: "@@@udanup"
        MYSQL_DATABASE: db_simplewap
    volumes:
      - /opt/docker_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
